[package]
name = "extreme_performance_"
description = "extreme single pc performance"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
tokio.workspace = true
core_affinity = "0.8.3"
parking_lot.workspace = true
